### ISSUE TITLE
Issue in 0.2.0

### ISSUE THREAD

**Issue by raajwant** [BcdLib/PullComponent#2]
TypeError: Failed to fetch dynamically imported module: https://0.0.0.0/_content/BcdLib.PullComponent/dist/index.js

**Comment by zxyao145** [comment]
Hi @raajwant , How do you use it? I tested it on Android, and it can be used normally, including #1 




https://user-images.githubusercontent.com/24973084/196022234-71911297-085d-426e-aba0-29519d9f5f53.mp4

**Comment by zxyao145** [comment]
Sorry I reproduced it, but there is a problem with packaging. Please try to use 0.4.0.

**Comment by raajwant** [comment]
Thanks. 0.4.0 version works perfectly. Thanks once again.
